apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: hello
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: jmblog
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: jmblog
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: "324148959017.dkr.ecr.us-east-2.amazonaws.com/repo-jmblog-test:latest"
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]