apiVersion: v1
kind: Service
metadata:
  name: jmblog
  labels:
    app: jmblog
    tier: frontend
spec:
  selector:
    app: jmblog
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmblog
  labels:
    app: jmblog
    tier: frontend
spec:
  selector:
    matchLabels:
      app: jmblog
      tier: frontend
      track: stable
      environment: qas
  replicas: 1
  template:
    metadata:
      labels:
        app: jmblog
        tier: frontend
        track: stable
        environment: qas
      annotations:
        version: "0.0.1"
    spec:
      containers:
      - name: nginx
        image: "324148959017.dkr.ecr.us-east-2.amazonaws.com/repo-jmblog-front-test:af6758df831ad3e2623cfdbbdb87c5cdb9d01d55"
        ports:
          - name: http
            containerPort: 80
        resources:      
          requests:        
            cpu: 200m
            memory: 128Mi
        env:    
          - name: ENV_VAR01
            value: var01_value    
          - name: ENV_VAR02
            value: var01_value
      imagePullSecrets:
        - name: myregistrykey